Fix #118
openforcefield/openff-fragmenter pull request #123
Opened 2021-08-11 10:39 UTC by jthorton

## Description
Fixes #118 by making fragmeter continue to grow the fragment until the sterochemistry can be fixed. The error is normally caused by new stereocenters being formed whereby enumerating the stereochemistry can not fix the issue, instead we continue to grow the fragment to remove the new centre until we return the parent molecule.

I can confirm this now works for the example I posted in the issue, `[H][O][C]([H])([H])[C]([H])([H])[C]([H])([N]([H])[C]1=[N][C]([H])=[C]2[C](=[N]1)[N]([C]([H])([H])[H])[C](=[O])[C]([O][C]1=[C]([F])[C]([H])=[C]([F])[C]([H])=[C]1[H])=[C]2[H])[C]([H])([H])[C]([H])([H])[O][H]`

![image](https://user-images.githubusercontent.com/30259414/129015266-a69e75ff-ae75-473b-8627-4a9f56cfb8ab.png)

## Status
- [ ] Ready to go

2021-08-17 13:05 UTC, SimonBoothroyd requested changes
Just a few changes requested to clean-up the APIs a bit but once those are made this LGTM! Thanks for adding this patch

2021-08-17 13:05 UTC, SimonBoothroyd commented on openff/fragmenter/fragment.py
> +        fragment, correct_stereo = cls._atom_bond_set_to_mol(
```suggestion
        fragment, has_new_stereocenter = cls._atom_bond_set_to_mol(
```

2021-08-18 11:38 UTC, jthorton commented on openff/fragmenter/fragment.py
> +    ) -> Tuple[Molecule, bool]:
Good call that will be better!

2021-08-18 13:24 UTC, SimonBoothroyd commented
Thanks for these changes @jthorton - could you also update `L1418` of `fragment.py` so that it returns `None, False`?

2021-08-18 13:35 UTC, jthorton commented
Good catch - done in [6fbee70](https://github.com/openforcefield/openff-fragmenter/pull/123/commits/6fbee700becce2983013c4a7f153a6c7088323c8)

2021-08-18 15:02 UTC, SimonBoothroyd approved these changes
Thanks @jthorton - I think this should be good to go!

2021-08-18 15:13 UTC, merged